### ISSUE TITLE
Wiki has a minor typo

### ISSUE THREAD

**Issue by jsantos42** [pulgamecanica/42Portfolio#49]
I tried to create a PR, but I don't have access permissions to the wiki repo

<img width="644" alt="Screenshot 2023-07-25 at 11 11 31" src="https://github.com/pulgamecanica/42Portfolio/assets/79864209/54e0226b-5c2a-4616-8eb8-0a5baf5600f4">

<img width="642" alt="Screenshot 2023-07-25 at 11 10 33" src="https://github.com/pulgamecanica/42Portfolio/assets/79864209/10e2f979-d2fc-4071-a9eb-edc0fcc75acf">

**Comment by pulgamecanica** [comment]
Hello @jsantos42 thanks a lot fixing this typo. I do have the write access to the Wiki reserved for only collaborators of the project.

I've invited you to be a collaborator so you can finally contribute to this OpenSource Project!

Cheers

**Comment by jsantos42** [comment]
Hey @pulgamecanica! Thank you!
I just pushed it to the `jsantos-fix-wiki-typo` branch, though it does not appear in the select-branch dropdown (PR section)

It [seems](https://stackoverflow.com/questions/10642928/how-can-i-make-a-pull-request-for-a-wiki-page-on-github) adding a PR for wiki is not possible

**Comment by pulgamecanica** [comment]
You can edit the Wiki directly I believe

**Comment by jsantos42** [comment]
Dude....🙈 I'll go back to my cave now and ease my shame!
done, thanks!
